"""
web/pwa_inject.py — Post-processes the pygbag build output to add PWA support.

Run after building with pygbag:
    python -m pygbag --build web_main.py
    python web/pwa_inject.py [--version <tag>]

What it does:
  1. Generates icon-192.png and icon-512.png from assets/icon/icon.png
  2. Copies web/manifest.json into build/web/
  3. Generates a service-worker.js that pre-caches every file in build/web/
     (so the app works offline after the first visit)
  4. Patches build/web/index.html to register the manifest and service worker
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

ROOT      = Path(__file__).resolve().parent.parent
BUILD_DIR = ROOT / "build" / "web"
WEB_DIR   = ROOT / "web"
ICON_SRC  = ROOT / "assets" / "icon" / "icon.png"


# ── icon generation ───────────────────────────────────────────────────────────

def _generate_icons() -> None:
    try:
        from PIL import Image  # type: ignore
    except ImportError:
        print("WARNING: Pillow not installed — skipping icon generation.")
        print("         Install with: pip install Pillow")
        return

    if not ICON_SRC.exists():
        print(f"WARNING: {ICON_SRC} not found — skipping icon generation.")
        return

    try:
        img = Image.open(ICON_SRC).convert("RGBA")
        for size in (192, 512):
            out = BUILD_DIR / f"icon-{size}.png"
            img.resize((size, size), Image.LANCZOS).save(out)
            print(f"  icon-{size}.png")
    except Exception as exc:
        print(f"WARNING: icon generation failed: {exc} — skipping.")


# ── service worker ────────────────────────────────────────────────────────────

def _collect_files() -> list[str]:
    """Return a list of all cache-able paths relative to BUILD_DIR."""
    skip = {"service-worker.js"}
    # Include root URL so navigating to "./' works offline
    files: list[str] = ["./"]
    for f in sorted(BUILD_DIR.rglob("*")):
        if f.is_file() and f.name not in skip:
            rel = f.relative_to(BUILD_DIR)
            files.append("./" + str(rel).replace("\\", "/"))
    return files


def _write_service_worker(files: list[str], version: str) -> None:
    cache_name = f"aquarium98-{version}"

    # Small critical files are pre-cached during SW install (fast, reliable).
    # Large assets (WASM, Python packages) are cached lazily on first fetch so
    # that a single slow/failed file can't block the entire SW installation.
    small_ext  = {".html", ".json", ".png", ".ico", ".css", ".js"}
    precache   = [f for f in files if Path(f).suffix.lower() in small_ext
                  or f == "./"]
    files_json = json.dumps(precache, indent=2)

    sw = f"""\
// Auto-generated by pwa_inject.py — do not edit manually.
// Cache name includes version so stale caches are replaced on each deploy.
const CACHE_NAME = "{cache_name}";

// Small critical files are pre-cached at install time.
// Large assets (WASM, Python packages) are cached lazily on first fetch.
const PRECACHE_FILES = {files_json};

self.addEventListener("install", event => {{
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then(cache => cache.addAll(PRECACHE_FILES))
      .then(() => self.skipWaiting())
  );
}});

self.addEventListener("activate", event => {{
  // No clients.navigate() here — that would interrupt the 94 MB archive
  // download mid-flight when a new SW activates.  The navigation-first fetch
  // strategy already ensures index.html is always fresh on the next load.
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(
        keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
}});

// Navigation requests: network-first so index.html always reflects the latest
// deploy.  Falls back to the cached copy only when offline.  This prevents the
// service worker from serving a stale index.html (and therefore a stale autorun
// or Python config) to users after a new release is deployed.
// All other assets remain cache-first for speed + offline support.
self.addEventListener("fetch", event => {{
  if (event.request.mode === "navigate") {{
    event.respondWith(
      fetch(event.request)
        .then(response => {{
          if (response && response.ok) {{
            const cloned = response.clone();
            caches.open(CACHE_NAME).then(cache => cache.put(event.request, cloned));
          }}
          return response;
        }})
        .catch(() => caches.match("./index.html"))
    );
    return;
  }}
  event.respondWith(
    caches.match(event.request).then(cached => {{
      if (cached) return cached;
      return fetch(event.request).then(response => {{
        if (response && response.ok) {{
          const cloned = response.clone();
          caches.open(CACHE_NAME).then(cache => cache.put(event.request, cloned));
        }}
        return response;
      }});
    }})
  );
}});
"""
    (BUILD_DIR / "service-worker.js").write_text(sw, encoding="utf-8")
    print(f"  service-worker.js  (cache: {cache_name}, {len(precache)} pre-cached + {len(files) - len(precache)} lazy)")


# ── index.html patch ──────────────────────────────────────────────────────────

_PWA_HEAD = """\
  <link rel="manifest" href="manifest.json">
  <meta name="theme-color" content="#000080">
  <style>
    /* Black background so any letterbox/pillarbox gaps are invisible. */
    html, body { background: #000 !important; margin: 0; padding: 0; }
  </style>
  <script>
    if ("serviceWorker" in navigator) {
      window.addEventListener("load", () => {
        navigator.serviceWorker.register("service-worker.js")
          .then(r  => console.log("[SW] registered:", r.scope))
          .catch(e => console.warn("[SW] registration failed:", e));
      });
    }
    // Hide the xterm.js pyconsole so it does not push the game canvas off to
    // the side. The terminal was force-shown during debugging; production build
    // hides it so the game canvas fills the full browser viewport.
    window.addEventListener("load", () => {
      var pc = document.getElementById("pyconsole");
      if (pc) { pc.hidden = true; }
    });
  </script>"""

# ── Python template patches ────────────────────────────────────────────────────

# Patch 0 — wrap start_toplevel with console.log for diagnosis.
# NOTE: aio.cross.simulator is intentionally NOT set here.  Setting
# simulator=True blocks ALL CDN activity, including the pygame download,
# leaving pygame as an empty stub with no attributes.  start_toplevel
# does not scan user code so it does not hang; CDN is safe to enable.
_TOPLEVEL_OLD = (
    "    # start async top level machinery if not started and add a console in any case if requested.\n"
    "    await TopLevel_async_handler.start_toplevel(platform.shell, console=window.python.config.debug)\n"
)
_TOPLEVEL_NEW = (
    "    platform.window.console.log('[pwa] calling start_toplevel')\n"
    "    # start async top level machinery if not started and add a console in any case if requested.\n"
    "    await TopLevel_async_handler.start_toplevel(platform.shell, console=window.python.config.debug)\n"
    "    platform.window.console.log('[pwa] start_toplevel done')\n"
)

# Patch 1 — remove the MM.UME blocking loop.
# MM.UME is a read-only getter on Pygbag's MediaManager; setting it from JS
# silently fails, so the loop never exits.
_UME_OLD = (
    "        while not platform.window.MM.UME:\n"
    "            await asyncio.sleep(.1)\n"
)
_UME_NEW = (
    "        # pwa_inject.py: MM.UME gate bypassed.\n"
    "        platform.window.infobox.innerText = 'Starting Aquarium 98...'\n"
    "        await asyncio.sleep(0)\n"
)

# Patch 2 — replace TopLevel_async_handler.preload_code with a no-op.
# preload_code scans imports, calls async_repos (CDN) and pip_install (PyPI).
# Even though async_repos completes quickly, pip_install for our bundled
# modules (window_web, aquarium, src…) tries to download from PyPI and hangs.
# TopLevel_async_handler is already in scope (defined in cpythonrc.py loaded
# from CDN before the template runs), so we can patch it directly — no fragile
# module attribute tricks needed.
_SOURCE_OLD = (
    "    await shell.source(main, callback=ui_callback)\n"
)
# Two-step approach:
# Step 1: run shell.source on a minimal "import pygame" script so that
#   preload_code downloads pygame from the CDN.  We can't skip this step
#   because with simulator=False (required for CDN), preload_code would
#   also try to pip-install our custom modules (window_web, aquarium) and
#   hang.  The minimal script has only stdlib/CDN imports, so preload_code
#   finishes quickly.
# Step 2: exec our real main.py directly (explicit namespace → __file__ is
#   set correctly; no preload_code scanning our module graph).
_SOURCE_NEW = (
    "    # pwa_inject.py: two-step load — CDN preload for pygame, then direct exec.\n"
    "    import os as _pwa_os, sys as _pwa_sys\n"
    "    _pwa_main_path = str(main)  # save before preload can overwrite main in globals\n"
    "    platform.window.infobox.innerText = 'Loading pygame...'\n"
    "    await asyncio.sleep(0)\n"
    "    # Step 1: minimal script so preload_code downloads pygame from CDN.\n"
    "    _pwa_pg_path = '/data/data/aquarium98/_pwa_pygame.py'\n"
    "    open(_pwa_pg_path, 'w').write(\n"
    "        'import pygame\\nimport asyncio\\nasync def main():\\n    pass\\nasyncio.run(main())\\n'\n"
    "    )\n"
    "    try:\n"
    "        await shell.source(Path(_pwa_pg_path), callback=ui_callback)\n"
    "        platform.window.console.log('[pwa] pygame preload done, has_init=' + str(hasattr(_pwa_sys.modules.get('pygame', object()), 'init')))\n"
    "    except Exception as _pwa_pg_e:\n"
    "        platform.window.console.log('[pwa] pygame preload warning: ' + repr(_pwa_pg_e))\n"
    "    # Step 2: exec our actual main.py with __file__ and template globals.\n"
    "    platform.window.console.log('[pwa] loading game, main.py exists=' + str(_pwa_os.path.exists(_pwa_main_path)))\n"
    "    platform.window.infobox.innerText = 'Loading game...'\n"
    "    await asyncio.sleep(0)\n"
    "    try:\n"
    "        with open(_pwa_main_path) as _f:\n"
    "            _src = _f.read()\n"
    "        _ns = {**globals(), '__file__': _pwa_main_path, '__name__': '__main__'}\n"
    "        exec(compile(_src, _pwa_main_path, 'exec'), _ns)\n"
    "        platform.window.console.log('[pwa] exec returned (game loop scheduled)')\n"
    "    except Exception as _e:\n"
    "        import traceback as _tb\n"
    "        platform.window.console.log('[pwa] EXEC FAILED: ' + repr(_e))\n"
    "        platform.window.console.log('[pwa] ' + _tb.format_exc()[:800])\n"
    "        platform.window.infobox.innerText = 'EXEC FAILED: ' + str(_e)[:200]\n"
    "        platform.window.infobox.style.display = 'block'\n"
    "        platform.window.infobox.style.background = 'darkred'\n"
    "        platform.window.infobox.style.color = 'white'\n"
    "        raise\n"
)


# Patch 4 — replace synchronous tar.extractall() with async iteration.
# tarfile.extractall() is blocking: on a 94 MB archive it holds the JS event
# loop for 30-60+ seconds, making the browser appear completely frozen/crashed.
# Replacing it with tar.next() + tar.extract() called one-file-at-a-time, with
# await asyncio.sleep(0) every 50 files, keeps the browser responsive and gives
# users a visible progress indicator while the archive unpacks.
# The filter='tar' kwarg requires Python 3.12 — pygbag 0.9.3 bundles 3.12. ✓
_EXTRACTALL_OLD = (
    "            tar = tarfile.open(fileobj=archive, mode=\"r:gz\")\n"
    "            tar.extractall(path=appdir.as_posix(), filter='tar')\n"
    "            tar.close()\n"
)
_EXTRACTALL_NEW = (
    "            tar = tarfile.open(fileobj=archive, mode=\"r:gz\")\n"
    "            platform.window.infobox.innerText = 'Extracting files...'\n"
    "            await asyncio.sleep(0)\n"
    "            _n = 0\n"
    "            while True:\n"
    "                _m = tar.next()\n"
    "                if _m is None:\n"
    "                    break\n"
    "                tar.extract(_m, path=appdir.as_posix(), filter='tar')\n"
    "                _n += 1\n"
    "                if _n % 50 == 0:\n"
    "                    platform.window.infobox.innerText = f'Loading... ({_n} files extracted)'\n"
    "                    await asyncio.sleep(0)\n"
    "            platform.window.console.log('[pwa] extracted ' + str(_n) + ' files')\n"
    "            platform.window.infobox.innerText = 'Starting game...'\n"
    "            await asyncio.sleep(0)\n"
    "            tar.close()\n"
)


# Patch 5 — embed.counter() timeout.
# In custom_site mode, embed.counter() may never increment before shell.source
# starts the render loop (chicken-and-egg).  Cap the wait at 3 seconds and log
# the counter value so we can see whether this loop was the blocker.
_EMBED_COUNTER_OLD = (
    "    # wait preloading complete : that includes images and wasm compilation of bundled modules\n"
    "    while embed.counter()<0:\n"
    "        await asyncio.sleep(.1)\n"
)
_EMBED_COUNTER_NEW = (
    "    # wait preloading complete (pwa_inject: 3s timeout added)\n"
    "    _pwat = 0\n"
    "    while embed.counter()<0:\n"
    "        await asyncio.sleep(.1)\n"
    "        _pwat += 1\n"
    "        if _pwat >= 30:\n"
    "            platform.window.console.log('[pwa] embed.counter=' + str(embed.counter()) + ' after 3s, forcing continue')\n"
    "            break\n"
    "    platform.window.console.log('[pwa] embed.counter=' + str(embed.counter()))\n"
)

# Patch 6 — error wrapper for asyncio.run(custom_site()).
# Any unhandled exception in custom_site() (including NameError for undefined
# TopLevel_async_handler, FileNotFoundError for main.py, etc.) fails silently
# without this wrapper.  This catches everything and shows it in the console
# and infobox so we can diagnose startup failures.
_ASYNCIO_RUN_OLD = "asyncio.run( custom_site() )\n"
_ASYNCIO_RUN_NEW = (
    "async def _pwa_run():\n"
    "    try:\n"
    "        await custom_site()\n"
    "    except BaseException as _e:\n"
    "        import traceback as _tb\n"
    "        _m = _tb.format_exc()\n"
    "        try:\n"
    "            platform.window.console.log('[pwa] FATAL: ' + repr(_e))\n"
    "            platform.window.console.log('[pwa] ' + _m[:800])\n"
    "            platform.window.infobox.innerText = 'FATAL: ' + str(_e)[:200]\n"
    "            platform.window.infobox.style.display = 'block'\n"
    "            platform.window.infobox.style.background = 'darkred'\n"
    "            platform.window.infobox.style.color = 'white'\n"
    "        except Exception:\n"
    "            pass\n"
    "\n"
    "asyncio.run(_pwa_run())\n"
)

# Patch 7 — appdir.mkdir(exist_ok=True).
# On repeat page loads BrowserFS may have cached the directory from a previous
# session.  The default mkdir() raises FileExistsError which kills custom_site()
# before the archive is even extracted — silently, without our Patch 6 wrapper.
_MKDIR_OLD = "    appdir.mkdir()\n"
_MKDIR_NEW = "    appdir.mkdir(exist_ok=True)\n"


def _patch_html() -> None:
    html_path = BUILD_DIR / "index.html"
    if not html_path.exists():
        print("WARNING: build/web/index.html not found — skipping HTML patch.")
        return
    html = html_path.read_text(encoding="utf-8")
    # Use a unique marker so re-running is safe without skipping Python patches.
    if "<!-- pwa_inject: done -->" in html:
        print("  index.html already patched — skipping.")
        return

    # Patch 0: CDN bypass before start_toplevel (must come before Patch 2).
    if _TOPLEVEL_OLD in html:
        html = html.replace(_TOPLEVEL_OLD, _TOPLEVEL_NEW, 1)
        print("  index.html  (CDN bypass injected before start_toplevel)")
    else:
        print("  index.html  WARNING: start_toplevel line not found — template may have changed")

    # Patch 1: remove UME blocking loop.
    if _UME_OLD in html:
        html = html.replace(_UME_OLD, _UME_NEW, 1)
        print("  index.html  (UME blocking loop removed)")
    else:
        print("  index.html  WARNING: UME loop not found — template may have changed")

    # Patch 2: inject preload bypass unconditionally before shell.source.
    if _SOURCE_OLD in html:
        html = html.replace(_SOURCE_OLD, _SOURCE_NEW, 1)
        print("  index.html  (CDN preload bypass injected)")
    else:
        print("  index.html  WARNING: shell.source line not found — template may have changed")

    # Patch 3: set autorun:1 so Python launches immediately without requiring
    # a user click.  The JS-level UME gate (autorun:0 / ume_block:1) hides its
    # "click to start" prompt in the terminal strip below the canvas — invisible
    # to users who only see the grey game area.  With autorun:1 Python starts at
    # once; audio stays silent until the first canvas interaction (Chrome's
    # autoplay policy), which is normal game UX.
    # pygbag may format this as "autorun":0 or autorun : 0 depending on version.
    autorun_patched = re.sub(r'"?autorun"?\s*:\s*0', 'autorun : 1', html, count=1)
    if autorun_patched != html:
        html = autorun_patched
        print("  index.html  (autorun:1 — Python starts without user click)")
    else:
        print("  index.html  WARNING: autorun:0 not found — already set or template changed")

    # Patch 4: async tar extraction — keeps browser responsive during unpack.
    if _EXTRACTALL_OLD in html:
        html = html.replace(_EXTRACTALL_OLD, _EXTRACTALL_NEW, 1)
        print("  index.html  (async tar extraction with progress indicator)")
    else:
        print("  index.html  WARNING: tar.extractall line not found — template may have changed")

    # Patch 5: embed.counter() timeout.
    if _EMBED_COUNTER_OLD in html:
        html = html.replace(_EMBED_COUNTER_OLD, _EMBED_COUNTER_NEW, 1)
        print("  index.html  (embed.counter timeout + diagnostic)")
    else:
        print("  index.html  WARNING: embed.counter loop not found — template may have changed")

    # Patch 6: asyncio.run error wrapper.
    if _ASYNCIO_RUN_OLD in html:
        html = html.replace(_ASYNCIO_RUN_OLD, _ASYNCIO_RUN_NEW, 1)
        print("  index.html  (asyncio.run error wrapper)")
    else:
        print("  index.html  WARNING: asyncio.run(custom_site()) not found — template may have changed")

    # Patch 7: appdir.mkdir(exist_ok=True) — safe on repeat loads.
    if _MKDIR_OLD in html:
        html = html.replace(_MKDIR_OLD, _MKDIR_NEW, 1)
        print("  index.html  (appdir.mkdir exist_ok=True)")
    else:
        print("  index.html  WARNING: appdir.mkdir() not found — template may have changed")

    html = html.replace("</head>", _PWA_HEAD + "\n<!-- pwa_inject: done -->\n</head>", 1)
    html_path.write_text(html, encoding="utf-8")
    print("  index.html  (manifest + SW registration injected)")


# ── main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Inject PWA support into pygbag build output.")
    parser.add_argument("--version", default="dev", help="Version string for the service-worker cache name.")
    args = parser.parse_args()

    if not BUILD_DIR.exists():
        print(f"ERROR: {BUILD_DIR} not found.", file=sys.stderr)
        print("       Run 'python -m pygbag --build web_main.py' first.", file=sys.stderr)
        sys.exit(1)

    print(f"Injecting PWA support into {BUILD_DIR}/")

    print("Generating icons ...")
    _generate_icons()

    print("Copying manifest.json ...")
    shutil.copy(WEB_DIR / "manifest.json", BUILD_DIR / "manifest.json")
    print("  manifest.json")

    print("Writing service worker ...")
    files = _collect_files()
    _write_service_worker(files, args.version)

    print("Patching index.html ...")
    _patch_html()

    print("Done — PWA support added.")
    print()
    print("After deploying, users can click 'Install' in Chrome/Edge to add")
    print("Aquarium 98 as a standalone offline desktop/mobile app.")


if __name__ == "__main__":
    main()
