"""
web/pwa_inject.py — Post-processes the pygbag build output to add PWA support.

Run after building with pygbag:
    python -m pygbag --build web_main.py
    python web/pwa_inject.py [--version <tag>]

What it does:
  1. Generates icon-192.png and icon-512.png from assets/icon/icon.png
  2. Copies web/manifest.json into build/web/
  3. Generates a service-worker.js that pre-caches every file in build/web/
     (so the app works offline after the first visit)
  4. Patches build/web/index.html to register the manifest and service worker
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

ROOT      = Path(__file__).resolve().parent.parent
BUILD_DIR = ROOT / "build" / "web"
WEB_DIR   = ROOT / "web"
ICON_SRC  = ROOT / "assets" / "icon" / "icon.png"


# ── icon generation ───────────────────────────────────────────────────────────

def _generate_icons() -> None:
    try:
        from PIL import Image  # type: ignore
    except ImportError:
        print("WARNING: Pillow not installed — skipping icon generation.")
        print("         Install with: pip install Pillow")
        return

    if not ICON_SRC.exists():
        print(f"WARNING: {ICON_SRC} not found — skipping icon generation.")
        return

    try:
        img = Image.open(ICON_SRC).convert("RGBA")
        for size in (192, 512):
            out = BUILD_DIR / f"icon-{size}.png"
            img.resize((size, size), Image.LANCZOS).save(out)
            print(f"  icon-{size}.png")
    except Exception as exc:
        print(f"WARNING: icon generation failed: {exc} — skipping.")


# ── service worker ────────────────────────────────────────────────────────────

def _collect_files() -> list[str]:
    """Return a list of all cache-able paths relative to BUILD_DIR."""
    skip = {"service-worker.js"}
    # Include root URL so navigating to "./' works offline
    files: list[str] = ["./"]
    for f in sorted(BUILD_DIR.rglob("*")):
        if f.is_file() and f.name not in skip:
            rel = f.relative_to(BUILD_DIR)
            files.append("./" + str(rel).replace("\\", "/"))
    return files


def _write_service_worker(files: list[str], version: str) -> None:
    cache_name = f"aquarium98-{version}"

    # Small critical files are pre-cached during SW install (fast, reliable).
    # Large assets (WASM, Python packages) are cached lazily on first fetch so
    # that a single slow/failed file can't block the entire SW installation.
    small_ext  = {".html", ".json", ".png", ".ico", ".css", ".js"}
    precache   = [f for f in files if Path(f).suffix.lower() in small_ext
                  or f == "./"]
    files_json = json.dumps(precache, indent=2)

    sw = f"""\
// Auto-generated by pwa_inject.py — do not edit manually.
// Cache name includes version so stale caches are replaced on each deploy.
const CACHE_NAME = "{cache_name}";

// Small critical files are pre-cached at install time.
// Large assets (WASM, Python packages) are cached lazily on first fetch.
const PRECACHE_FILES = {files_json};

self.addEventListener("install", event => {{
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then(cache => cache.addAll(PRECACHE_FILES))
      .then(() => self.skipWaiting())
  );
}});

self.addEventListener("activate", event => {{
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(
        keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k))
      )
    ).then(() => self.clients.claim())
  );
}});

// Cache-first for assets; navigation requests fall back to index.html
// so the app loads correctly offline regardless of the URL entered.
// Large assets not in PRECACHE_FILES are cached lazily on first fetch.
self.addEventListener("fetch", event => {{
  if (event.request.mode === "navigate") {{
    event.respondWith(
      caches.match("./index.html").then(r => r || fetch(event.request))
    );
    return;
  }}
  event.respondWith(
    caches.match(event.request).then(cached => {{
      if (cached) return cached;
      return fetch(event.request).then(response => {{
        if (response && response.ok) {{
          const cloned = response.clone();
          caches.open(CACHE_NAME).then(cache => cache.put(event.request, cloned));
        }}
        return response;
      }});
    }})
  );
}});
"""
    (BUILD_DIR / "service-worker.js").write_text(sw, encoding="utf-8")
    print(f"  service-worker.js  (cache: {cache_name}, {len(precache)} pre-cached + {len(files) - len(precache)} lazy)")


# ── index.html patch ──────────────────────────────────────────────────────────

_PWA_HEAD = """\
  <link rel="manifest" href="manifest.json">
  <meta name="theme-color" content="#000080">
  <script>
    if ("serviceWorker" in navigator) {
      window.addEventListener("load", () => {
        navigator.serviceWorker.register("service-worker.js")
          .then(r  => console.log("[SW] registered:", r.scope))
          .catch(e => console.warn("[SW] registration failed:", e));
      });
    }
  </script>"""

# ── Python template patches ────────────────────────────────────────────────────

# Patch 1 — remove the MM.UME blocking loop.
# MM.UME is a read-only getter on Pygbag's MediaManager; setting it from JS
# silently fails, so the loop never exits.
_UME_OLD = (
    "        while not platform.window.MM.UME:\n"
    "            await asyncio.sleep(.1)\n"
)
_UME_NEW = (
    "        # pwa_inject.py: MM.UME gate bypassed.\n"
    "        platform.window.infobox.innerText = 'Starting Aquarium 98...'\n"
    "        await asyncio.sleep(0)\n"
)

# Patch 2 — replace TopLevel_async_handler.preload_code with a no-op.
# preload_code scans imports, calls async_repos (CDN) and pip_install (PyPI).
# Even though async_repos completes quickly, pip_install for our bundled
# modules (window_web, aquarium, src…) tries to download from PyPI and hangs.
# TopLevel_async_handler is already in scope (defined in cpythonrc.py loaded
# from CDN before the template runs), so we can patch it directly — no fragile
# module attribute tricks needed.
_SOURCE_OLD = (
    "    await shell.source(main, callback=ui_callback)\n"
)
# preload_code() has a single flag: `if not aio.cross.simulator:` that gates
# ALL network activity (check_list, pip_install, PyPI lookups).  Setting
# aio.cross.simulator = True skips it entirely while still letting preload_code
# run the important os.chdir / sys.path setup at the top of the function.
# This is simpler and more reliable than patching class methods.
_SOURCE_NEW = (
    "    # pwa_inject.py: skip CDN/PyPI package checks (all deps are bundled).\n"
    "    try:\n"
    "        import aio.cross as _aio_cross\n"
    "        _aio_cross.simulator = True\n"
    "    except Exception as _pwa_e:\n"
    "        print('pwa simulator bypass:', _pwa_e)\n"
    "    platform.window.infobox.innerText = 'Loading game...'\n"
    "    await asyncio.sleep(0)\n"
    "    await shell.source(main, callback=ui_callback)\n"
)


def _patch_html() -> None:
    html_path = BUILD_DIR / "index.html"
    if not html_path.exists():
        print("WARNING: build/web/index.html not found — skipping HTML patch.")
        return
    html = html_path.read_text(encoding="utf-8")
    # Use a unique marker so re-running is safe without skipping Python patches.
    if "<!-- pwa_inject: done -->" in html:
        print("  index.html already patched — skipping.")
        return

    # Patch 1: remove UME blocking loop.
    if _UME_OLD in html:
        html = html.replace(_UME_OLD, _UME_NEW, 1)
        print("  index.html  (UME blocking loop removed)")
    else:
        print("  index.html  WARNING: UME loop not found — template may have changed")

    # Patch 2: inject preload bypass unconditionally before shell.source.
    if _SOURCE_OLD in html:
        html = html.replace(_SOURCE_OLD, _SOURCE_NEW, 1)
        print("  index.html  (CDN preload bypass injected)")
    else:
        print("  index.html  WARNING: shell.source line not found — template may have changed")

    # Patch 3: set autorun:1 so Python launches immediately without requiring
    # a user click.  The JS-level UME gate (autorun:0 / ume_block:1) hides its
    # "click to start" prompt in the terminal strip below the canvas — invisible
    # to users who only see the grey game area.  With autorun:1 Python starts at
    # once; audio stays silent until the first canvas interaction (Chrome's
    # autoplay policy), which is normal game UX.
    # pygbag may format this as "autorun":0 or autorun : 0 depending on version.
    autorun_patched = re.sub(r'"?autorun"?\s*:\s*0', 'autorun : 1', html, count=1)
    if autorun_patched != html:
        html = autorun_patched
        print("  index.html  (autorun:1 — Python starts without user click)")
    else:
        print("  index.html  WARNING: autorun:0 not found — already set or template changed")

    html = html.replace("</head>", _PWA_HEAD + "\n<!-- pwa_inject: done -->\n</head>", 1)
    html_path.write_text(html, encoding="utf-8")
    print("  index.html  (manifest + SW registration injected)")


# ── main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Inject PWA support into pygbag build output.")
    parser.add_argument("--version", default="dev", help="Version string for the service-worker cache name.")
    args = parser.parse_args()

    if not BUILD_DIR.exists():
        print(f"ERROR: {BUILD_DIR} not found.", file=sys.stderr)
        print("       Run 'python -m pygbag --build web_main.py' first.", file=sys.stderr)
        sys.exit(1)

    print(f"Injecting PWA support into {BUILD_DIR}/")

    print("Generating icons ...")
    _generate_icons()

    print("Copying manifest.json ...")
    shutil.copy(WEB_DIR / "manifest.json", BUILD_DIR / "manifest.json")
    print("  manifest.json")

    print("Writing service worker ...")
    files = _collect_files()
    _write_service_worker(files, args.version)

    print("Patching index.html ...")
    _patch_html()

    print("Done — PWA support added.")
    print()
    print("After deploying, users can click 'Install' in Chrome/Edge to add")
    print("Aquarium 98 as a standalone offline desktop/mobile app.")


if __name__ == "__main__":
    main()
